// Lista de referencia para autocompletar el alta de activos. No pretende ser
// exhaustiva (los mercados listan miles de instrumentos y las composiciones
// cambian con el tiempo): cubre las acciones y ETFs más conocidos de EE.UU.
// y los principales emisores de la Bolsa de Valores de Colombia (BVC). Si un
// activo no aparece acá, se puede cargar manualmente como siempre.
export interface ReferenceStock {
  ticker: string;
  name: string;
  exchange: string;
  currencyCode: string;
}

const US_STOCKS: ReferenceStock[] = [
  { ticker: "AAPL", name: "Apple Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Clase A)", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "GOOG", name: "Alphabet Inc. (Clase C)", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "COST", name: "Costco Wholesale Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CMCSA", name: "Comcast Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "INTC", name: "Intel Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "QCOM", name: "QUALCOMM Incorporated", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "TXN", name: "Texas Instruments Incorporated", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "INTU", name: "Intuit Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "AMAT", name: "Applied Materials Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "MDLZ", name: "Mondelez International Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ADI", name: "Analog Devices Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "LRCX", name: "Lam Research Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Incorporated", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "SNPS", name: "Synopsys Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CDNS", name: "Cadence Design Systems Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "KLAC", name: "KLA Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "MRNA", name: "Moderna Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ORLY", name: "O'Reilly Automotive Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ROST", name: "Ross Stores Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "FAST", name: "Fastenal Company", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ODFL", name: "Old Dominion Freight Line Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CTAS", name: "Cintas Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "PAYX", name: "Paychex Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "MNST", name: "Monster Beverage Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "EA", name: "Electronic Arts Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ILMN", name: "Illumina Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "EXC", name: "Exelon Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "XEL", name: "Xcel Energy Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "WBA", name: "Walgreens Boots Alliance Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "BIIB", name: "Biogen Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "DXCM", name: "DexCom Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ZM", name: "Zoom Video Communications Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "DOCU", name: "DocuSign Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "TEAM", name: "Atlassian Corporation", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "WDAY", name: "Workday Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ZS", name: "Zscaler Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "DDOG", name: "Datadog Inc.", exchange: "NASDAQ", currencyCode: "USD" },

  { ticker: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "BAC", name: "Bank of America Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "WFC", name: "Wells Fargo & Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "C", name: "Citigroup Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MS", name: "Morgan Stanley", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "JNJ", name: "Johnson & Johnson", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "PG", name: "Procter & Gamble Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "KO", name: "Coca-Cola Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "PFE", name: "Pfizer Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "XOM", name: "Exxon Mobil Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CVX", name: "Chevron Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "WMT", name: "Walmart Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "HD", name: "Home Depot Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DIS", name: "Walt Disney Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "V", name: "Visa Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MA", name: "Mastercard Incorporated", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "UNH", name: "UnitedHealth Group Incorporated", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CAT", name: "Caterpillar Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "BA", name: "Boeing Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "GE", name: "General Electric Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "IBM", name: "International Business Machines Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MCD", name: "McDonald's Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "NKE", name: "Nike Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "T", name: "AT&T Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CVS", name: "CVS Health Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "RTX", name: "RTX Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "LMT", name: "Lockheed Martin Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "NOC", name: "Northrop Grumman Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "GD", name: "General Dynamics Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MMM", name: "3M Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "AXP", name: "American Express Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "TRV", name: "Travelers Companies Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "EMR", name: "Emerson Electric Co.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ETN", name: "Eaton Corporation plc", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ITW", name: "Illinois Tool Works Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "PH", name: "Parker-Hannifin Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ROK", name: "Rockwell Automation Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CMI", name: "Cummins Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DE", name: "Deere & Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "F", name: "Ford Motor Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "GM", name: "General Motors Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DAL", name: "Delta Air Lines Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "UAL", name: "United Airlines Holdings Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "AAL", name: "American Airlines Group Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "LUV", name: "Southwest Airlines Co.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MAR", name: "Marriott International Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "HLT", name: "Hilton Worldwide Holdings Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "YUM", name: "Yum! Brands Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CL", name: "Colgate-Palmolive Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "KMB", name: "Kimberly-Clark Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "GIS", name: "General Mills Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "HSY", name: "Hershey Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "SYY", name: "Sysco Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "KR", name: "Kroger Co.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "TGT", name: "Target Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "TJX", name: "TJX Companies Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "BBY", name: "Best Buy Co. Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DG", name: "Dollar General Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DLTR", name: "Dollar Tree Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "ORCL", name: "Oracle Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CRM", name: "Salesforce Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ACN", name: "Accenture plc", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "LLY", name: "Eli Lilly and Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ABBV", name: "AbbVie Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DHR", name: "Danaher Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ABT", name: "Abbott Laboratories", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "AMGN", name: "Amgen Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "CI", name: "Cigna Group", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "ELV", name: "Elevance Health Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "HUM", name: "Humana Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "SO", name: "Southern Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DUK", name: "Duke Energy Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "NEE", name: "NextEra Energy Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "AEP", name: "American Electric Power Company Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "D", name: "Dominion Energy Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "SLB", name: "Schlumberger Limited", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "COP", name: "ConocoPhillips", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "OXY", name: "Occidental Petroleum Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "PSX", name: "Phillips 66", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "VLO", name: "Valero Energy Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "MPC", name: "Marathon Petroleum Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "SPG", name: "Simon Property Group Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "PLD", name: "Prologis Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "AMT", name: "American Tower Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "CCI", name: "Crown Castle Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "EQIX", name: "Equinix Inc.", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "PSA", name: "Public Storage", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "O", name: "Realty Income Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "DOW", name: "Dow Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "LIN", name: "Linde plc", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "APD", name: "Air Products and Chemicals Inc.", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "SHW", name: "Sherwin-Williams Company", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "NEM", name: "Newmont Corporation", exchange: "NYSE", currencyCode: "USD" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", exchange: "NYSE", currencyCode: "USD" },
];

const US_ETFS: ReferenceStock[] = [
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF Trust", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", exchange: "NASDAQ", currencyCode: "USD" },
  { ticker: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "LQD", name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "GLD", name: "SPDR Gold Shares", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "SLV", name: "iShares Silver Trust", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "ARKK", name: "ARK Innovation ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLB", name: "Materials Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "XLC", name: "Communication Services Select Sector SPDR Fund", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", exchange: "NYSE Arca", currencyCode: "USD" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", exchange: "NASDAQ", currencyCode: "USD" },
];

// Principales emisores activos de la Bolsa de Valores de Colombia (BVC).
// La BVC tiene un universo mucho más chico que EE.UU., pero igual pueden
// existir cambios (fusiones, exclusiones) que esta lista no refleje — si tu
// especie no aparece, cargala manualmente.
const CO_STOCKS: ReferenceStock[] = [
  { ticker: "ECOPETROL", name: "Ecopetrol S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFBCOLOM", name: "Bancolombia S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "BCOLOMBIA", name: "Bancolombia S.A. (Ordinaria)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFAVAL", name: "Grupo Aval Acciones y Valores S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "GRUPOAVAL", name: "Grupo Aval Acciones y Valores S.A. (Ordinaria)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFGRUPSURA", name: "Grupo de Inversiones Suramericana S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "GRUPOSURA", name: "Grupo de Inversiones Suramericana S.A. (Ordinaria)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFGRUPOARG", name: "Grupo Argos S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "GRUPOARGOS", name: "Grupo Argos S.A. (Ordinaria)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFCEMARGOS", name: "Cementos Argos S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "CEMARGOS", name: "Cementos Argos S.A. (Ordinaria)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "ISA", name: "Interconexión Eléctrica S.A. E.S.P.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "GEB", name: "Grupo Energía Bogotá S.A. E.S.P.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "CELSIA", name: "Celsia S.A. E.S.P.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "NUTRESA", name: "Grupo Nutresa S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "CORFICOLCF", name: "Corporación Financiera Colombiana S.A. (Corficolombiana)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "BOGOTA", name: "Banco de Bogotá S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "PFDAVVNDA", name: "Banco Davivienda S.A. (Preferencial)", exchange: "BVC", currencyCode: "COP" },
  { ticker: "ETB", name: "Empresa de Telecomunicaciones de Bogotá S.A. E.S.P.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "MINEROS", name: "Mineros S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "CNEC", name: "Canacol Energy Ltd.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "FABRICATO", name: "Fabricato S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "ENKA", name: "Enka de Colombia S.A.", exchange: "BVC", currencyCode: "COP" },
  { ticker: "TABLEMAC", name: "Tablemac S.A.", exchange: "BVC", currencyCode: "COP" },
];

export const REFERENCE_STOCKS: ReferenceStock[] = [...US_STOCKS, ...US_ETFS, ...CO_STOCKS];

export function searchReferenceStocks(query: string, limit = 15): ReferenceStock[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  const starts = REFERENCE_STOCKS.filter((s) => s.ticker.startsWith(q));
  const contains = REFERENCE_STOCKS.filter(
    (s) => !s.ticker.startsWith(q) && (s.ticker.includes(q) || s.name.toUpperCase().includes(q)),
  );
  return [...starts, ...contains].slice(0, limit);
}
